FROM crosskd-train:v3

# Define o diretório de trabalho
WORKDIR /workspace
COPY . .

# Permissões corretas
RUN chmod -R a+rX /workspace && \
    chmod +x /workspace/crosskd/CrossKD/tools/custom_test.py

RUN pip install --no-cache-dir \
    onnxruntime \
    onnxruntime-gpu \
    pycocotools \
    tqdm \
    opencv-python-headless \
    numpy

# Comando default
CMD ["python3", "-u", "/workspace/crosskd/CrossKD/tools/custom_test.py"]
