FROM crosskd-train:v3

WORKDIR /workspace
COPY . .

WORKDIR /workspace/CrossKD


RUN chmod -R a+rX /workspace && chmod +x /workspace/CrossKD/tools/train.py

CMD ["python3", "-u", "/workspace/CrossKD/tools/train.py", "/workspace/CrossKD/configs/crosskd/gfl_test_config.py", "--work-dir", "/proj/aurora/Smartness/checkpoints-CQI"]
