FROM crosskd-test:v1

WORKDIR /workspace
COPY . .

WORKDIR /workspace//CrossKD

RUN chmod -R a+rX /workspace && chmod +x /workspace/CrossKD/tools/test.py

CMD ["python3", "-u", "/workspace/CrossKD/tools/test.py", "/workspace/CrossKD/configs/crosskd+pkd/crosskd+pkd_r50_gflv1_r101-2x-ms_fpn_1x_coco.py", "/proj/aurora/Smartness/checkpoints-pkd/epoch_12.pth", "--work-dir", "/proj/aurora/Smartness/test"]
