FROM crosskd-train:v3
# Definir diretório de trabalho como o CrossKD
WORKDIR /workspace/CrossKD

# Copiar todo o projeto CrossKD para o workspace
COPY crosskd/CrossKD /workspace/CrossKD

# Copiar MMDeploy para dentro do workspace
COPY mmdeploy /workspace/CrossKD/mmdeploy

RUN pip install /workspace/CrossKD/mmdeploy && pip install "numpy<2"

# Garantir permissões
RUN chmod -R a+rX /workspace/CrossKD


# Comando para exportar ONNX
CMD ["python3", "/workspace/CrossKD/mmdeploy/tools/deploy.py", \
     "mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py", \
     "/proj/aurora/Smartness/checkpoints-GFLV1/crosskd_r50_gflv1_r101-2x-ms_fpn_1x_coco.py", \
     "/proj/aurora/Smartness/checkpoints-GFLV1/epoch_12.pth", \
     "demo/demo.jpg", \
     "--work-dir", "/proj/aurora/Smartness/checkpoints-GFLV1/onnx_temp", \
     "--device", "cuda:0"]
