#FROM crosskd-train:v3
FROM onnx-converter:v1
# Definir diretório de trabalho como o CrossKD
WORKDIR /workspace/CrossKD

# Copiar todo o projeto CrossKD para o workspace
COPY crosskd/CrossKD /workspace/CrossKD

# Copiar MMDeploy para dentro do workspace
COPY mmdeploy /workspace/CrossKD/mmdeploy

#RUN pip install /workspace/CrossKD/mmdeploy && pip install "numpy<2"
#RUN pip uninstall -y onnxruntime onnxruntime-gpu && pip install onnxruntime-gpu==1.15.1


# Garantir permissões
RUN chmod -R a+rX /workspace/CrossKD


# Comando para exportar ONNX
CMD ["python3", "/workspace/CrossKD/mmdeploy/tools/deploy.py", \
     "mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py", \
     "configs/gfl/gfl_r101_fpn_ms-2x_coco.py", \
     "/proj/aurora/Smartness/gfl-teacher-checkpoint/gfl_r101_fpn_mstrain_2x_coco_20200629_200126-dd12f847.pth", \
     "/proj/aurora/Smartness/data/coco/test2017/000000290680.jpg", \
     "--work-dir", "/proj/aurora/Smartness/gfl-teacher-checkpoint/onnx_model", \
     "--device", "cpu", \
     "--dump-info"]
