# Base com CUDA 11.7 runtime e Ubuntu 20.04
#FROM nvidia/cuda:11.7.1-runtime-ubuntu20.04
FROM custom-test:v1
# Definir diretório de trabalho
WORKDIR /workspace/CrossKD

# Usar mirror confiável e instalar Python3 + pip
#RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://br.archive.ubuntu.com/ubuntu/|g' /etc/apt/sources.list \
# && apt-get update \
# && apt-get install -y --fix-missing \
#      python3 python3-pip python3-setuptools ca-certificates \
#      git wget curl build-essential \
# && rm -rf /var/lib/apt/lists/*

# Copiar projeto CrossKD e MMDeploy
COPY crosskd/CrossKD /workspace/CrossKD
COPY mmdeploy /workspace/CrossKD/mmdeploy

# Atualizar pip
#RUN pip3 install --upgrade pip

#RUN pip3 uninstall -y onnxruntime onnxruntime-gpu || true && \
#    pip3 install --no-cache-dir onnxruntime-gpu==1.16.1 --extra-index-url https://download.pytorch.org/whl/cu117 && \
#    pip3 install --no-cache-dir opencv-python-headless==4.8.1.78 pycocotools mmdeploy-runtime-gpu==1.3.1



# Instalar apenas runtime necessário para inferência ONNX
#RUN pip3 install --no-cache-dir \
#      onnxruntime-gpu==1.16.0 \
#      pycocotools \
#      mmdeploy-runtime-gpu==1.3.1

#ENV LD_LIBRARY_PATH=/usr/local/lib/python3.8/dist-packages/onnxruntime:/usr/local/cuda/lib64:$CONDA_PREFIX/lib:/usr/local/lib:$LD_LIBRARY_PATH


ENV LD_LIBRARY_PATH=/opt/onnxruntime/lib:$LD_LIBRARY_PATH


# Garantir permissões corretas
RUN chmod -R 755 /workspace/CrossKD

# Variáveis de ambiente CUDA

ENV CONDA_PREFIX=/opt/conda
ENV CUDA_HOME=/usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH


# Comando padrão
CMD ["python3", "-u", "tools/custom_test.py"]
